#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ifnone": "00_core.ipynb",
         "PROJECT": "01_defaults.ipynb",
         "LEVEL": "01_defaults.ipynb",
         "DATA": "01_defaults.ipynb",
         "NORM_CSV": "01_defaults.ipynb",
         "MODELS": "01_defaults.ipynb",
         "MODEL": "01_defaults.ipynb",
         "SIZE": "01_defaults.ipynb",
         "BATCH_SIZE": "01_defaults.ipynb",
         "LOSS": "01_defaults.ipynb",
         "REDUCTION": "01_defaults.ipynb",
         "EPOCHS": "01_defaults.ipynb",
         "DROPOUT": "01_defaults.ipynb",
         "LR": "01_defaults.ipynb",
         "WD": "01_defaults.ipynb",
         "WEIGHT": "01_defaults.ipynb",
         "NORMALIZER": "01_defaults.ipynb",
         "hparams": "02_params.ipynb",
         "get_items": "03_data_read.ipynb",
         "ImageLoader": "04_data_loaders.ipynb",
         "MaskLoader": "04_data_loaders.ipynb",
         "CategoryLoader": "04_data_loaders.ipynb",
         "MyDataset": "05_data_dataset.ipynb",
         "ClassDataset": "05_data_dataset.ipynb",
         "ImageClassifDataset": "05_data_dataset.ipynb",
         "ImageSegmentDataset": "05_data_dataset.ipynb",
         "NormDataset": "05_data_dataset.ipynb",
         "SplitDataset": "05_data_dataset.ipynb",
         "np_to_tensor": "05_data_dataset.ipynb",
         "TensorDataset": "05_data_dataset.ipynb",
         "show_img": "06_data_utils.ipynb"}

modules = ["core.py",
           "defaults.py",
           "params.py",
           "data/read.py",
           "data/loaders.py",
           "data/dataset.py",
           "data/utils.py"]

git_url = "https://github.com/schwobr/grade_classif_nbdev/tree/master/"

def custom_doc_links(name): return None