#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00a_defaults.ipynb (unless otherwise specified).

__all__ = ['PROJECT', 'LEVEL', 'DATA', 'NORM_CSV', 'MODELS', 'MODEL', 'SIZE', 'BATCH_SIZE', 'LOSS', 'REDUCTION',
           'EPOCHS', 'DROPOUT', 'LR', 'WD', 'WEIGHT', 'NORMALIZER']

#Cell
from pathlib import Path

#Cell
_PROJECT = Path('/home/DeepLearning/grades_classif')
PROJECT = Path('/work/stages/schwob/grades_classif')
LEVEL = 2
_DATA = Path(f'/data/DeepLearning/SCHWOB_Robin/Patches_240/Patches_MGI_240_{LEVEL}')
DATA = Path(f'/work/stages/schwob/Patches_240/Patches_MGI_240_{LEVEL}')
_MODELS = Path('/data/DeepLearning/SCHWOB_Robin/models')
NORM_CSV = PROJECT/'categories.csv'
MODELS = PROJECT/'models'
MODEL = 'resnet34'
SIZE = 224
BATCH_SIZE = 16
LOSS = 'mse'
REDUCTION = 'mean'
EPOCHS = 10
DROPOUT= 0.5
LR = 1e-3
WD = 0.01
WEIGHT = 1.
NORMALIZER = MODELS/f'uf_norm_b1_{LEVEL}_240_1.pth'