#AUTOGENERATED! DO NOT EDIT! File to edit: dev/_train_normalizer.ipynb (unless otherwise specified).

__all__ = ['model']

#Cell
from .params import hparams
from .models.pl_modules import Normalizer

#Cell
model = Normalizer(hparams)

#Cell
model.fit()