#AUTOGENERATED! DO NOT EDIT! File to edit: dev/03_train_normalizer.ipynb (unless otherwise specified).

__all__ = ['model']

#Cell
from .params import hparams
from .models.pl_modules import Normalizer

#Cell
model = Normalizer(hparams)