#AUTOGENERATED! DO NOT EDIT! File to edit: dev/_train_classif.ipynb (unless otherwise specified).

__all__ = []

#Cell
from .params.parser import hparams
from .train import train_classifier

#Cell
train_classifier(hparams)