#AUTOGENERATED! DO NOT EDIT! File to edit: dev/_train_normalizer.ipynb (unless otherwise specified).

__all__ = ['model']

#Cell
from .params.parser import hparams
from .train import train_normalizer

#Cell
model = train_normalizer(hparams)