#AUTOGENERATED! DO NOT EDIT! File to edit: dev/_train_discriminator.ipynb (unless otherwise specified).

__all__ = []

#Cell
from .params.parser import hparams
from .train import train_discriminator
from .imports import *

#Cell
train_discriminator(hparams)