#AUTOGENERATED! DO NOT EDIT! File to edit: dev/14_data.transforms.ipynb (unless otherwise specified).

__all__ = ['get_transforms']

#Cell
from albumentations import (RandomRotate90,
                            Flip,
                            Transpose,
                            GridDistortion,
                            RandomCrop,
                            GaussianBlur,
                            RandomGamma,
                            RGBShift)

#Cell
def get_transforms(size):
    tfms = [RandomRotate90(),
            Flip(),
            Transpose(),
            GridDistortion(distort_limit=0.05, p=0.2),
            RandomGamma(p=0.2),
            GaussianBlur(blur_limit=3, p=0.2),
            RGBShift(0.15, 0.15, 0.15),
            RandomCrop(size, size)]
    val_tfms = [RandomCrop(size, size)]
    return tfms, val_tfms