#AUTOGENERATED! DO NOT EDIT! File to edit: dev/13_data_utils.ipynb (unless otherwise specified).

__all__ = ['show_img']

#Cell
import matplotlib.pyplot as plt

#Cell
def show_img(x, ax=None, figsize=(3,3), title=None, hide_axis=True, cmap='viridis', alpha=None, **kwargs):
    if ax is None: fig,ax = plt.subplots(figsize=figsize)
    xtr = dict(cmap=cmap, alpha=alpha, **kwargs)
    ax.imshow(x, **xtr)
    if hide_axis: ax.axis('off')
    if title: ax.set_title(title)
    return ax