# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/80_params.defaults.ipynb (unless otherwise specified).

__all__ = ['PROJECT', 'CSVS', 'LEVEL', 'DATA', 'DATA_CSV', 'MODELS', 'COORD_CSV', 'PATCH_CLASSES', 'OPEN_MODE',
           'SAMPLE_MODE', 'MODEL', 'GPUS', 'SIZE', 'BATCH_SIZE', 'LOSS', 'SCHED', 'REDUCTION', 'EPOCHS', 'DROPOUT',
           'LR', 'WD', 'WEIGHT', 'NORMALIZER', 'PRED_LEVELS', 'SCAN', 'FILT', 'TRANSFORMS', 'RESUME', 'TRAIN_PERCENT',
           'TOPK']

# Cell
from pathlib import Path

# Cell
PROJECT = Path('/home/DeepLearning/grade_classif')
_PROJECT = Path('/work/stages/schwob/grade_classif')
CSVS = PROJECT/'csvs'
LEVEL = 1
DATA = FULL_DATA/f'Patches_1024_{LEVEL}'
DATA_CSV = CSVS/f'scans.csv'
MODELS = Path('/data/DeepLearning/SCHWOB_Robin/models/logs')
COORD_CSV = DATA/'coords.csv'
_MODELS = PROJECT/'models/logs'
_PATCH_CLASSES = DATA/'patch_classes.csv'
PATCH_CLASSES = None
OPEN_MODE = 'RGB'
SAMPLE_MODE = 1
MODEL = 'cbr_3_32_4'
GPUS = [1]
SIZE = 299
BATCH_SIZE = 64
LOSS = 'cross-entropy'
SCHED = 'one-cycle'
REDUCTION = 'mean'
EPOCHS = 5
DROPOUT= 0.5
LR = 1e-3
WD = 0.01
WEIGHT = 2.
NORMALIZER = None
PRED_LEVELS = [1]
SCAN = None
FILT = None
TRANSFORMS = 1
RESUME = None
TRAIN_PERCENT = 1.
TOPK = 5