# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/20_models.plmodules.ipynb (unless otherwise specified).

__all__ = ['get_base_model', 'get_head', 'BaseDataModule', 'BaseModule', 'NormDataModule', 'Normalizer',
           'ImageClassifDataModule', 'ClassifModel', 'RNNAttention', 'MILDataModule', 'get_topk_idxs', 'get_max_probs',
           'MILModel', 'RNNAggDataModule', 'RNNAggregator', 'CoTeachingModel']

# Cell
from copy import deepcopy

import pytorch_lightning as pl
from kornia.color import rgb_to_grayscale, rgb_to_hsv
from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning.loggers import CometLogger
from pytorch_lightning.profiler import AdvancedProfiler, SimpleProfiler
from torch.optim import Optimizer
from torch.optim.lr_scheduler import CosineAnnealingLR, OneCycleLR, ReduceLROnPlateau
from torch.utils.data import DataLoader, Dataset, RandomSampler, WeightedRandomSampler

from ..core import ifnone
from ..data.color import rgb_to_e, rgb_to_h, rgb_to_heg, rgb_to_lab
from ..data.dataset import (
    ImageClassifDataset,
    MILDataset,
    NormDataset,
    RNNSlideDataset,
)
from ..data.transforms import *
from ..data.utils import show_img
from ..imports import *
from .losses import BCE, FocalLoss
from .metrics import pcc, ssim
from .modules import *
from .utils import (
    gaussian_mask,
    get_num_features,
    get_sizes,
    named_leaf_modules,
)

# Cell
_open_functions = {
    "LAB": rgb_to_lab,
    "HSV": rgb_to_hsv,
    "3G": rgb_to_grayscale,
    "H": rgb_to_h,
    "E": rgb_to_e,
    "HEG": rgb_to_heg,
    "RGB": lambda x: x
}

# Cell
def _get_loss(
    loss_name: str, weight: float, reduction: str, device: str = "cpu", nc: int = 2
) -> Callable[[torch.Tensor, torch.Tensor], torch.Tensor]:
    if loss_name == "cross-entropy":
        loss = nn.CrossEntropyLoss(
            torch.tensor([weight] + [1.0] * (nc - 1), device=device),
            reduction=reduction,
        )
    elif loss_name == "bce":
        loss = BCE(
            reduction=reduction, pos_weight=torch.tensor([1 / weight], device=device)
        )
    elif loss_name == "mse":
        loss = nn.MSELoss(reduction=reduction)
    elif loss_name == "focal":
        loss = FocalLoss(reduction=reduction)
    return loss.__call__

# Cell
def _get_scheduler(
    opt: Optimizer, name: str, total_steps: int, lr: float
) -> torch.optim.lr_scheduler._LRScheduler:
    if name == "one-cycle":
        sched = OneCycleLR(opt, lr, total_steps=total_steps)
        interval = "step"
    elif name == "cosine-anneal":
        sched = CosineAnnealingLR(opt, total_steps)
        interval = "step"
    elif name == "reduce-on-plateau":
        sched = ReduceLROnPlateau(opt)
        interval = "epoch"
    else:
        return None
    return {"scheduler": sched, "interval": interval}

# Cell
def get_base_model(model_name: str, pretrained: bool = True):
    if "cbr" in model_name:
        args = map(int, model_name.split("_")[1:])
        base_model = CBR(*args)
        cut = -3
    elif "sasa" in model_name:
        args = map(int, model_name.split("_")[1:])
        base_model = SASA(*args)
        cut = -3
    elif "sanet" in model_name:
        splits = model_name.split("_")
        kernel_size = int(splits[-1])
        base_model = globals()[splits[0]](kernel_size)
        cut = -2
    else:
        base_model = timm.create_model(
            model_name, pretrained=pretrained
        )
        cut = -2
    base_model = nn.Sequential(*list(base_model.children())[:cut])
    return base_model

# Cell
def get_head(n_features: int, n_classes: int, dropout: float = 0.5):
    head = [nn.AdaptiveAvgPool2d(1), nn.Flatten()]
    head += bn_drop_lin(n_features, n_features, p=dropout / 2) + bn_drop_lin(
        n_features, n_classes, p=dropout
    )
    head = nn.Sequential(*head)
    return head

# Cell
class BaseDataModule(pl.LightningDataModule):
    def __init__(
        self,
        datafolder: Path,
        data_csv: Path,
        batch_size: int = 32,
        size: int = 299,
        transforms: Optional[int] = None,
        patch_classes: Optional[Path] = None,
        concepts: Optional[Path] = None,
        concept_classes: Optional[Path] = None,
        train_percent: float = 1,
        get_id: Optional[Callable[[Any], str]] = None,
        **kwargs,
    ):
        super().__init__()
        self.datafolder = datafolder
        self.data_csv = data_csv
        self.batch_size = batch_size
        self.patch_classes = patch_classes
        self.concepts = concepts
        self.concept_classes = concept_classes
        self.size = size
        self.transforms = transforms
        self.train_percent = train_percent
        self.get_id = get_id
        if transforms is not None:
            tfm_func = globals()[f"get_transforms{transforms}"]
            self.tfms = tfm_func(size)
        else:
            self.tfms = None

    def train_dataloader(self) -> DataLoader:
        return DataLoader(
            self.data.train,
            batch_size=self.batch_size,
            shuffle=True,
            drop_last=True,
            num_workers=4,
            pin_memory=True,
        )

    def val_dataloader(self) -> DataLoader:
        # OPTIONAL
        # can also return a list of val dataloaders
        return DataLoader(
            self.data.valid, batch_size=self.batch_size, num_workers=4, pin_memory=True
        )

    def test_dataloader(self) -> DataLoader:
        # OPTIONAL
        # can also return a list of test dataloaders
        if self.data.test is not None:
            return DataLoader(self.data.test, batch_size=self.batch_size)
        else:
            return None

    def get_filt(self) -> Optional[Callable[[Path], bool]]:
        if self.patch_classes is not None:
            patch_classes_df = pd.read_csv(self.patch_classes, index_col="patchId")
            x_type = patch_classes_df.loc[x.stem, "type"]
            if self.filt != "all":

                def filt(x):
                    return x_type == self.filt

            else:

                def filt(x):
                    return x_type != "garb"

        elif self.concepts is not None and self.concept_classes is not None:
            conc_classes_df = pd.read_csv(self.concept_classes, index_col=0)
            if self.filt != "all":
                ok = conc_classes_df.loc[
                    conc_classes_df["type"] == self.filt
                ].index.values
            else:
                ok = conc_classes_df.loc[conc_classes_df["type"] != "garb"].index.values
            conc_df = pd.read_csv(self.concepts, index_col="patchId")

            def filt(x):
                return conc_df.loc[x.stem, "concept"] in ok

        else:
            filt = None
        return filt

    def show_some(self, n: int = 8, split: str = "train", imgsize: int = 4):
        fig, axs = plt.subplots(n, 2, figsize=(imgsize * 2, imgsize * n))
        data = getattr(self.data, split)
        idxs = np.random.choice(np.arange(len(data)), size=n, replace=False)
        for ax_r, idx in zip(axs, idxs):
            x, x_tfmed = data.get_orig_tfmed(idx)
            show_img(x, ax=ax_r[0])
            show_img(x_tfmed, ax=ax_r[1])
        title = "original/transformed"
        fig.suptitle(title)
        plt.show()

# Cell
class BaseModule(pl.LightningModule):
    """"""

    def __init__(
        self,
        size: int = 299,
        gpus: Optional[List[int]] = None,
        model: Optional[str] = None,
        normalizer: Optional[str] = None,
        metrics: Optional[List[Callable[..., Number]]] = None,
        savedir: Optional[Union[Path, str]] = None,
        level: int = None,
        resume: Optional[str] = None,
        sample_mode: int = 0,
        weight: float = 1,
        epochs: int = 5,
        loss: str = "mse",
        reduction: str = "mean",
        lr: float = 1e-3,
        wd: float = 0.01,
        train_percent: float = 1.0,
        sched: Optional[str] = None,
        rand_weights: bool = False,
        dropout: float = 0.5,
        version: Optional[str] = None,
        open_mode: str = "RGB",
        mixed_precision: bool = False,
        **kwargs,
    ):
        super().__init__()
        if model is None and normalizer is None:
            raise AttributeError(
                "at least one of model and normalizer should ne specified"
            )
        self.main_device = "cpu" if gpus is None else f"cuda:{gpus[0]}"
        # self.main_device = 'cuda:1'
        self.metrics = ifnone(metrics, [])
        model_type = "normalizer" if isinstance(self, Normalizer) else "classifier"
        model_name = model if model_type == "classifier" else normalizer
        savedir = ifnone(savedir, Path.cwd() / "log")
        level = ifnone(level, -1)
        self.save_path = Path(savedir) / f"level_{level}"
        self.save_path = self.save_path / f"{model_type}/{model_name}"
        self.save_hyperparameters()

    def post_init(self):
        leaf_modules = named_leaf_modules(self)
        size = self.hparams.size
        self.sizes, self.leaf_modules = get_sizes(
            self, input_shape=(3, size, size), leaf_modules=leaf_modules
        )
        self = self.to(self.main_device)
        if self.hparams.resume is not None:
            self.load(self.hparams.resume)

    def on_train_start(self):
        self.train()

    def training_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> torch.Tensor:
        # REQUIRED
        x, y = batch
        y_hat = self(x)
        loss = self.loss(y_hat, y)
        lr = self.sched.optimizer.param_groups[-1]["lr"]
        log = {"train_loss": loss.detach(), "learning_rate": lr}
        self.log_dict(log, on_step=True, on_epoch=False)
        return loss

    def validation_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> torch.Tensor:
        # OPTIONAL
        x, y = batch
        y_hat = self(x)
        loss = self.loss(y_hat, y).detach()
        self.log("val_loss", loss)
        return loss

    def test_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> torch.Tensor:
        # OPTIONAL
        return self.validation_step(batch, batch_nb)

    def on_fit_end(self):
        path = self.trainer.checkpoint_callbacks[0].best_model_path
        checkpoint = torch.load(path, map_location=self.main_device)
        self.load_state_dict(checkpoint["state_dict"])
        self.export_to_torchscript()

    def configure_optimizers(self) -> Union[Optimizer, Dict[str, Any]]:
        # REQUIRED
        hparams = self.hparams
        try:
            weight = hparams.weight if hparams.sample_mode == 0 else 1.0
        except AttributeError:
            weight = 1.0
        if not hasattr(self, "loss"):
            self.loss = _get_loss(
                hparams.loss, weight, hparams.reduction, device=self.main_device
            )
        self.lr = hparams.lr
        self.wd = hparams.wd
        self.opt = torch.optim.Adam(self.parameters(), lr=self.lr)
        n_train_dl = len(self.trainer.datamodule.train_dataloader())
        n_iter = int(hparams.epochs * n_train_dl)
        sched = _get_scheduler(self.opt, hparams.sched, n_iter, self.lr)
        if sched is None:
            return self.opt
        else:
            self.sched = sched["scheduler"]
            return {"optimizer": self.opt, "lr_scheduler": sched}

    def on_after_backward(self):
        for pg in self.opt.param_groups:
            for p in pg["params"]:
                p.data.mul_(1 - self.wd * pg["lr"])

    def load(self, version: str, ckpt_epoch: int = None):
        """
        Load a specific `version` of current model, stored in
        `self.save_path/lightning_logs`. If multiple checkpoints have been
        stored, `ckpt_epoch` can be specified to load a specific epoch. Else
        the latest epoch is loaded.
        """
        save_dir = self.save_path / f"lightning_logs/version_{version}/checkpoints"
        try:
            path = (
                list(save_dir.iterdir())[-1]
                if ckpt_epoch is None
                else save_dir / f"_ckpt_epoch_{ckpt_epoch}.ckpt"
            )
        except:
            path = save_dir / f"epoch={ckpt_epoch}.ckpt"
        checkpoint = torch.load(path, map_location=self.main_device)
        self.load_state_dict(checkpoint["state_dict"])

    def my_summarize(self) -> pd.DataFrame:
        """
        Get a DataFrame containing the list of all leaf modules of current
        model, with their corresponding output shape.
        """
        named_modules = list(map(lambda x: x.name, self.leaf_modules))
        summary = pd.DataFrame({"Name": named_modules, "Output Shape": self.sizes})
        return summary

    def fit(self, dm: pl.LightningDataModule, monitor="val_loss", **kwargs):
        """
        Fit the model using parameters stored in `hparams`.
        """
        logger = CometLogger(
            api_key=os.environ["COMET_API_KEY"],
            workspace="schwobr",
            save_dir=self.save_path,
            project_name="grade-classif",
        )
        logger.experiment.add_tag("norm" if isinstance(self, Normalizer) else "classif")
        ckpt_path = (
            self.save_path
            / "lightning_logs"
            / f"version_{logger.version}"
            / "checkpoints"
        )
        if not ckpt_path.is_dir():
            ckpt_path.mkdir(parents=True)
        mode = "min" if "loss" in monitor or "err" in monitor else "max"
        ckpt_callback = ModelCheckpoint(
            dirpath=ckpt_path, save_top_k=3, monitor=monitor, save_last=True, mode=mode
        )
        profiler = None
        if self.hparams.profiler == "simple":
            profiler = SimpleProfiler(ckpt_path.parent / "profiler_logs.txt")
        elif self.hparams.profiler == "advanced":
            profiler = AdvancedProfiler(ckpt_path.parent / "profiler_logs.txt")
        precision = 16 if self.hparams.mixed_precision else 32
        trainer = pl.Trainer(
            gpus=self.hparams.gpus,
            callbacks=[ckpt_callback],
            logger=logger,
            precision=precision,
            min_epochs=self.hparams.epochs,
            max_epochs=self.hparams.epochs,
            profiler=profiler,
            **kwargs,
        )
        self.version = trainer.logger.version
        trainer.fit(self, dm)

    def predict(self, x: torch.Tensor) -> torch.Tensor:
        """
        Make a prediction on batch `x`.
        """
        return self.eval()(x)

    def export_to_torchscript(self):
        save_dir = self.save_path / f"lightning_logs/version_{self.version}"
        self.to_torchscript(
            file_path=str(save_dir / "best_model.pt"),
            method="trace",
            example_inputs=torch.rand(
                2,
                3,
                self.hparams.size,
                self.hparams.size,
                dtype=torch.float,
                device=self.main_device,
            ),
        )

    def _create_normalizer(self):
        hparams = self.hparams
        if hparams.normalizer is not None:
            norm = torch.jit.load(hparams.normalizer, map_location=self.main_device)
            for p in norm.parameters():
                p.requires_grad = False
            norm = norm.to(self.main_device).eval()
            self.norm = norm.__call__

# Cell
class NormDataModule(BaseDataModule):
    def setup(self, stage: Optional[str] = None):
        data = NormDataset.from_folder(
            self.datafolder,
            extensions=[".png"],
            filterfunc=self.get_filt(),
            train_percent=self.train_percent,
        ).split_by_csv(self.data_csv)

        if self.transforms is not None:
            tfm_func = globals()[f"get_transforms{self.transforms}"]
            self.tfms = tfm_func(self.size, num_els=len(data.valid))

        self.data = data.to_tensor(tfms=self.tfms)

# Cell
def _get_keys_in_list_and_apply(
    list_of_dicts: Sequence[Dict[str, Any]],
    *keys,
    apply_func: Optional[Callable[[Any], Any]] = None
) -> List[List[Any]]:
    res = []
    for k in keys:
        sub_list = []
        for d in list_of_dicts:
            sub_list.append(d[k])
        if apply_func is not None:
            sub_list = apply_func(sub_list)
        res.append(sub_list)
    return res

# Cell
class Normalizer(BaseModule):
    """"""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        input_shape = (3, self.hparams.size, self.hparams.size)
        self.unet = DynamicUnet(
            self.hparams.model,
            n_classes=3,
            input_shape=input_shape,
            pretrained=not self.hparams.rand_weights,
        )
        self.post_init()

    def on_epoch_start(self):
        for tfm in self.trainer.datamodule.data.valid.tfms:
            if "Deterministic" in str(type(tfm)):
                tfm.n = 0

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = _open_functions[self.hparams.open_mode](x).detach()
        return self.unet(x)

    def show_results(
        self, ds: Dataset, n: int = 16, imgsize: int = 4, title: Optional[str] = None
    ):
        """
        Plot `n` predictions from the normalizer using samples from dataset
        `ds`. Each line will contain input, target and prediction images (in
        that order).
        """
        n = min(n, self.bs)
        fig, axs = plt.subplots(n, 3, figsize=(imgsize * 3, imgsize * n))
        idxs = np.random.choice(np.arange(len(ds)), size=n, replace=False)
        inputs = []
        targs = []
        for idx in idxs:
            x, y = ds[idx]
            inputs.append(x)
            targs.append(y)
        inputs = torch.stack(inputs).to(next(self.main_device))
        preds = self.predict(inputs).clamp(0, 1)
        for ax_r, x, y, z in zip(axs, inputs, targs, preds):
            x = x.cpu().numpy().transpose(1, 2, 0)
            y = y.numpy().transpose(1, 2, 0)
            z = z.detach().cpu().numpy().transpose(1, 2, 0)
            show_img(x, ax=ax_r[0])
            show_img(y, ax=ax_r[1])
            show_img(z, ax=ax_r[2])
        title = ifnone(title, "input/target/prediction")
        fig.suptitle(title)
        plt.show()

    def freeze_encoder(self):
        """
        Freeze the encoder part of the normalizer.
        """
        for m in self.leaf_modules:
            if "encoder" in m.name and not isinstance(m, nn.BatchNorm2d):
                for param in m.parameters():
                    param.requires_grad = False

    def init_bn(self):
        """
        Initialize BatchNorm layers with bias `1e-3` and weights `1`.
        """
        for m in self.modules():
            if isinstance(m, nn.BatchNorm2d):
                with torch.no_grad():
                    m.bias.fill_(1e-3)
                    m.weight.fill_(1.0)

    def validation_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> Dict[str, torch.Tensor]:
        # OPTIONAL
        x, y = batch
        y_hat = self.predict(x)
        loss = self.loss(y_hat, y)
        ret = {"loss": loss}
        bs = y.shape[0]
        y = rgb_to_lab(y.detach())
        y_hat = rgb_to_lab(y_hat.detach())
        ret["mu_x"] = torch.mean(y[:, 0], axis=(1, 2))
        ret["sigma_x"] = torch.std(y[:, 0], axis=(1, 2))
        ret["mu_y"] = torch.mean(y_hat[:, 0], axis=(1, 2))
        ret["sigma_y"] = torch.std(y_hat[:, 0], axis=(1, 2))
        ret["mu_xy"] = torch.mean(y[:, 0] * y_hat[:, 0], axis=(1, 2))
        return ret

    def validation_epoch_end(self, outputs: List[Dict[str, torch.Tensor]]):
        # OPTIONAL
        log = {}
        mu_x, sigma_x, mu_y, sigma_y, mu_xy = get_keys_in_list_and_apply(
            outputs, "mu_x", "sigma_x", "mu_y", "sigma_y", "mu_xy", apply_func=torch.cat
        )
        m_ssim = ssim(mu_x, sigma_x, mu_y, sigma_y, mu_xy)
        m_pcc = pcc(mu_x, sigma_x, mu_y, sigma_y, mu_xy)
        m_cd = sigma_y / mu_y - sigma_x / mu_x
        log["ssim"] = m_ssim.mean()
        log["pcc"] = m_pcc.mean()
        log["cd"] = m_cd.mean()
        log["val_loss"] = torch.mean([output["loss"] for output in outputs])
        self.log_dict(log)

    def test_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> Dict[str, torch.Tensor]:
        return self.validation_step(batch, batch_nb)

    def test_epoch_end(self, outputs: List[Dict[str, torch.tensor]]):
        return self.validation_epoch_end(outputs)

# Cell
class ImageClassifDataModule(BaseDataModule):
    def __init__(
        self,
        datafolder: Path,
        data_csv: Path,
        classes: Sequence[str],
        label_func: Callable[[Path], str],
        sample_mode: int = 0,
        **kwargs
    ):
        super().__init__(datafolder, data_csv, **kwargs)
        self.classes = classes
        self.n_classes = len(classes)
        self.sample_mode = sample_mode
        self.label_func = label_func

    def setup(self, stage: Optional[str] = None):
        self.filt = self.get_filt()
        data = ImageClassifDataset.from_folder(
            self.datafolder,
            self.label_func,
            classes=self.classes,
            extensions=[".png"],
            include=self.classes,
            filterfunc=self.filt,
            train_percent=self.train_percent,
        ).split_by_csv(self.data_csv, get_id=self.get_id)
        n = len(data.train)
        self.weights = [
            np.float32(n / (data.train.labels == cl).sum()) for cl in self.classes
        ]
        self.data = data.to_tensor(tfms=self.tfms, tfm_y=False)

    def train_dataloader(self) -> DataLoader:
        sm = self.sample_mode
        w = self.weights
        labels = self.data.train.labels
        if sm > 0:
            weights = np.ones_like(labels, dtype=np.float32)
            for k, cl in enumerate(self.classes):
                weights[labels == cl] = w[k]
            if sm == 1:
                n = max([(labels == cl).sum() for cm in self.classes])
                sampler = WeightedRandomSampler(weights, int(self.n_classes * n))
            else:
                n = min([(labels == cl).sum() for cm in self.classes])
                sampler = WeightedRandomSampler(
                    weights, int(self.n_classes * n), replacement=False
                )
        else:
            sampler = RandomSampler(self.data.train)
        return DataLoader(
            self.data.train,
            batch_size=self.batch_size,
            sampler=sampler,
            drop_last=True,
            num_workers=4,
            pin_memory=True,
        )

# Cell
class ClassifModel(BaseModule):
    """"""

    def __init__(
        self, n_classes: int = 2, classes: Optional[Sequence[str]] = None, **kwargs
    ):
        super().__init__(**kwargs)
        classes = ifnone(classes, list(range(n_classes)))
        n_classes = len(classes)  # if classes is specified it superseeds n_classes
        self.save_hyperparameters()
        hparams = self.hparams
        self.loss = _get_loss(
            hparams.loss, 1.0, hparams.reduction, device=self.main_device, nc=n_classes
        )
        self.base_model = get_base_model(
            hparams.model, pretrained=not hparams.rand_weights
        )
        nf = get_num_features(self.base_model)
        self.head = get_head(nf, n_classes, dropout=hparams.dropout)
        self.post_init()
        self._create_normalizer()

    def validation_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> Dict[str, torch.Tensor]:
        # OPTIONAL
        x, y = batch
        y_hat = self(x).detach()
        loss = self.loss(y_hat, y).detach()
        ret = {"loss": loss}
        n = y.shape[0]
        y_hat = torch.softmax(y_hat, dim=1)
        y_hat = y_hat.argmax(dim=-1).view(n, -1)
        y = y.view(n, -1)
        for k, cl in enumerate(self.hparams.classes):
            ret[f"t_{cl}"] = ((y_hat == k) & (y == k)).float().sum()
            ret[f"f_{cl}"] = ((y_hat == k) & (y != k)).float().sum()
        return ret

    def validation_epoch_end(self, outputs: List[Dict[str, torch.Tensor]]):
        # OPTIONAL
        log = {}
        t_keys = [f"t_{cl}" for cl in self.hparams.classes]
        f_keys = [f"f_{cl}" for cl in self.hparams.classes]
        t = _get_keys_in_list_and_apply(outputs, *t_keys, apply_func=sum)
        f = _get_keys_in_list_and_apply(outputs, *f_keys, apply_func=sum)
        t = torch.stack(t)
        f = torch.stack(f)
        for metric in self.metrics:
            try:
                name = metric.__name__
            except AttributeError:
                name = metric.func.__name__
                kws = metric.keywords
                for k in kws:
                    name += f"_{k}_{kws[k]}"
            for k, cl in enumerate(self.hparams.classes):
                c_name = name + f"_{cl}"
                log[c_name] = metric(
                    t[k],
                    f[k],
                    t[:k].sum() + t[k + 1 :].sum(),
                    f[:k].sum() + f[k + 1 :].sum(),
                )
        log["val_loss"] = torch.mean(
            torch.stack([output["loss"] for output in outputs])
        )
        self.log_dict(log)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = _open_functions[self.hparams.open_mode](x).detach()
        if hasattr(self, "norm"):
            x = self.norm(x)
        x = self.base_model(x)
        x = self.head(x)
        return x

    def predict(self, x: torch.Tensor) -> torch.Tensor:
        pred = super().predict(x)
        pred = torch.softmax(pred, dim=1)
        return pred

    def freeze_base(self):
        """
        Freeze the base model.
        """
        for m in self.leaf_modules:
            if "base_model" in m.name and not isinstance(m, nn.BatchNorm2d):
                for param in m.parameters():
                    param.requires_grad = False

# Cell
class RNNAttention(BaseModule):
    """"""

    def __init__(
        self, n_glimpses: int = 3, glimpse_size: int = 256, gamma: float = 1, **kwargs
    ):
        super().__init__(**kwargs)
        hparams = self.hparams
        self.loss = _get_loss(
            hparams.loss, 1.0, hparams.reduction, device=self.main_device
        )
        nc = 2 if hparams.loss == "cross-entropy" else 1
        self.t_x = nn.Sequential(*list(CBR(3, 64, 2).children())[:-1])
        nf = get_num_features(self.t_x)
        self.fc = nn.Linear(nx, nc)
        self.t_l = nn.Sequential(
            nn.Linear(6, nf),
            nn.ReLU(),
            nn.Linear(nf, 2 * nf),
            nn.ReLU(),
            nn.Linear(2 * nf, nf),
        )
        self.t_a = nn.Sequential(
            nn.Linear(nf, 2 * nf),
            nn.ReLU(),
            nn.Linear(2 * nf, nf),
            nn.ReLU(),
            nn.Linear(nf, 6),
        )
        self.final_head = nn.Sequential(
            nn.Linear(nx * n_glimpses, nx), nn.ReLU(), nn.Linear(nf, nc)
        )
        self.save_hyperparameters()

    def forward(
        self, X: torch.Tensor, l: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        X = _open_functions[self.hparams.open_mode](X).detach()
        Ai = gaussian_mask(*l[:3], self.hparams.glimpse_size, self.hparams.size)
        Aj = gaussian_mask(*l[3:], self.hparams.glimpse_size, self.hparams.size)
        x = Ai[None, None] @ X @ Aj.T[None, None]
        if hasattr(self, "norm"):
            x = self.norm(x)
        fx = self.t_x(x)
        y = self.fc(fx)
        fl = self.t_l(l)
        l = torch.sigmoid(fx * fl)
        l = self.t_a(l)
        return fx, y, l

    def compute_loss(
        self, X: torch.Tensor, Y: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Compute the loss defined in the paper. Return the final slide-level
        prediction as well.
        """
        l0 = torch.tensor(
            [0, 0.5, self.hparams.size // self.hparams.glimpse_size] * 2,
            device=self.main_device,
        )
        loss = 0
        loss_prev = 0
        preds = []
        for t in range(self.hparams.n_glimpses):
            fx, y_hat, l = self(X, l0)
            fts.append(fx)
            loss += self.loss(y_hat, Y)
            loss_a = (y_hat ** 2).sum()
            if t > 0:
                loss -= loss_a - loss_prev / t
            loss_prev += loss_a
            loss += self.hparams.gamma * torch.exp(-torch.abs(l - l0))
            l0 = l.detach()
        # n_glimpses x bs x C
        fts = torch.cat(fts)
        fts = fts.view(fts.shape[1], -1)
        Y_hat = self.final_head(fts)
        loss += self.loss(Y_hat, Y)
        return loss, Y_hat

    def training_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> Dict[str, torch.Tensor]:
        # REQUIRED
        X, Y = batch
        loss, _ = self.compute_loss(X, Y)
        lr = self.sched.optimizer.param_groups[-1]["lr"]
        log = {"train_loss": loss, "learning_rate": lr}
        self.log_dict(log)
        return {"loss": loss}

    def validation_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> Dict[str, torch.Tensor]:
        # OPTIONAL
        x, y = batch
        y_hat = self(x)
        loss = self.loss(y_hat, y)
        ret = {"loss": loss}
        n = y.shape[0]
        if self.hparams.loss == "cross-entropy":
            y_hat = torch.softmax(y_hat, dim=1)
            y_hat = y_hat.argmax(dim=-1).view(n, -1)
        else:
            y_hat = torch.sigmoid(y_hat)
            y_hat = (y_hat > 0.5).view(n, -1)
        y = y.view(n, -1)
        ret["tp"] = ((y_hat) & (y == 1)).float().sum()
        ret["tn"] = ((~y_hat) & (y == 0)).float().sum()
        ret["fp"] = ((y_hat) & (y == 0)).float().sum()
        ret["fn"] = ((~y_hat) & (y == 1)).float().sum()
        return ret

    def validation_epoch_end(self, outputs: List[Dict[str, torch.Tensor]]):
        # OPTIONAL
        tp, fp, tn, fn = _get_keys_in_list_and_apply(
            outputs, "tp", "fp", "tn", "fn", apply_func=torch.sum
        )
        log = {}
        for metric in self.metrics:
            try:
                name = metric.__name__
            except AttributeError:
                name = metric.func.__name__
                kws = metric.keywords
                for k in kws:
                    name += f"_{k}_{kws[k]}"
            log[name] = metric(tp, fp, tn, fn)
        log["val_loss"] = torch.mean([output["loss"] for output in outputs])
        self.log_dict(log)

# Cell
class MILDataModule(BaseDataModule):
    def __init__(
        self,
        datafolder: Union[str, Path],
        data_csv: Union[str, Path],
        coord_csv: Union[str, Path],
        classes: Sequence[str],
        label_func: Optional[Callable[[Path], str]] = None,
        extensions: Optional[Sequence[str]] = None,
        level: int = 1,
        sample_mode: int = 0,
        **kwargs
    ):
        super().__init__(datafolder, data_csv, **kwargs)
        assert len(classes) == 2, "MIL only works with 2 classes."
        self.sample_mode = sample_mode
        self.coord_csv = coord_csv
        self.classes = classes
        self.label_func = ifnone(label_func, lambda x: x.parent.name)
        self.extensions = ifnone(extensions, ['.mrxs'])
        self.level = level

    def setup(self, stage: Optional[str] = None):
        self.data = (
            MILDataset.from_folder(
                self.datafolder,
                self.label_func,
                self.coord_csv,
                classes=self.classes,
                extensions=self.extensions,
                include=self.classes,
                train_percent=self.train_percent,
                size=self.size,
                level=self.level
            )
            .split_by_csv(self.data_csv)
            .to_tensor(tfms=self.tfms, tfm_y=False)
        )
        weights = np.float32(
            (self.data.train.labels == self.classes[0]).sum()
            / (self.data.train.labels == self.classes[1]).sum()
        )
        min_class = 1
        if weights < 1:
            weights = 1 / weights
            min_class = 0
        self.min_class = min_class
        self.weights = weights

    def train_dataloader(self) -> DataLoader:
        sm = self.sample_mode
        w = self.weights
        if sm > 0:
            labels = self.data.train.labels == self.classes[self.min_class]
            weights = np.where(labels, w, 1.0)
            if sm == 1:
                sampler = WeightedRandomSampler(weights, 2 * len(np.argwhere(~labels)))
            else:
                sampler = WeightedRandomSampler(weights,
                                                2*len(np.argwhere(labels)),
                                                replacement=False)
        else:
            sampler = RandomSampler(self.data.train)
        return DataLoader(
            self.data.train,
            batch_size=self.batch_size,
            sampler=sampler,
            drop_last=True,
            pin_memory=True,
        )

    def val_dataloader(self) -> DataLoader:
        # OPTIONAL
        # can also return a list of val dataloaders
        return DataLoader(
            self.data.valid,
            batch_size=self.batch_size,
            pin_memory=True,
        )

    def test_dataloader(self) -> DataLoader:
        return DataLoader(
            self.data.test,
            batch_size=self.batch_size,
            shuffle=False,
            pin_memory=True,
        )

# Cell
def get_topk_idxs(probs, slide_idxs, k=1):
    order = np.lexsort((probs, slide_idxs))
    probs = probs[order]
    slide_idxs = slide_idxs[order]
    index = np.empty(len(probs), 'bool')
    index[-k:] = True
    index[:-k] = slide_idxs[k:] != slide_idxs[:-k]
    idxs = order[index]
    return idxs

# Cell
def get_max_probs(probs, slide_idxs):
    nmax = slide_idxs.max()
    out = np.empty(nmax+1)
    out[:] = np.nan
    order = np.lexsort((probs, slide_idxs))
    probs = probs[order]
    slide_idxs = slide_idxs[order]
    index = np.empty(len(probs), 'bool')
    index[-1] = True
    index[:-1] = slide_idxs[1:] != slide_idxs[:-1]
    out[slide_idxs[index]] = probs[index]
    return out

# Cell
class MILModel(ClassifModel):
    """"""

    def __init__(self, topk: int = 1, **kwargs):
        super().__init__(n_classes=2, **kwargs)
        self.save_hyperparameters()

    def configure_optimizers(self):
        opt = super().configure_optimizers()
        if isinstance(opt, dict) and "lr_scheduler" in opt:
            n_slides = len(self.trainer.datamodule.data.test.slides)
            n_steps = (n_slides * self.hparams.topk) // self.hparams.batch_size
            opt["lr_scheduler"] = _get_scheduler(
                opt["optimizer"],
                self.hparams.sched,
                n_steps * self.hparams.epochs,
                self.hparams.lr,
            )
            self.sched = opt["lr_scheduler"]["scheduler"]
        return opt

    def on_train_epoch_start(self):
        self.trainer.verbose_test = False
        k = self.hparams.topk
        self.trainer.testting = True
        probs = _get_keys_in_list_and_apply(
            self.trainer.run_evaluation(test_mode=True)[0],
            "probs",
            apply_func=torch.cat,
        )[0]
        self.trainer.testing = False
        probs = probs.cpu().numpy()
        test_ds = self.trainer.datamodule.data.test
        slide_idxs = test_ds.slide_idxs
        idxs = get_topk_idxs(probs, slide_idxs, k=k)
        train_ds = self.trainer.datamodule.data.train
        train_ds.items = test_ds.items.copy()[idxs]
        train_ds.labels = test_ds.labels.copy()[idxs]
        train_ds.slide_idxs = test_ds.slide_idxs.copy()[idxs]
        self.trainer.reset_train_dataloader(self)

    def validation_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> Dict[str, torch.Tensor]:
        # OPTIONAL
        x, y = batch
        y_hat = self(x).detach()
        loss = self.loss(y_hat, y).detach()
        y_hat = torch.softmax(y_hat, dim=1)[:, 1]
        return {"probs": y_hat.clone(), "val_loss": loss}

    def validation_epoch_end(self, outputs: List[Dict[str, torch.Tensor]]):
        # OPTIONAL
        probs = _get_keys_in_list_and_apply(outputs, "probs", apply_func=torch.cat)[0]
        loss = _get_keys_in_list_and_apply(outputs, "val_loss", apply_func=torch.stack)[
            0
        ]
        probs = probs.cpu().numpy()
        log = {"val_loss": loss.mean()}
        val_ds = self.trainer.datamodule.data.valid
        maxs = get_max_probs(probs, val_ds.slide_idxs)
        preds = maxs > 0.5
        targs = np.array([val_ds.label_loader(label) for label in val_ds.slide_labels])
        tp = ((preds) & (targs == 1)).sum()
        tn = ((~preds) & (targs == 0)).sum()
        fp = ((preds) & (targs == 0)).sum()
        fn = ((~preds) & (targs == 1)).sum()
        for metric in self.metrics:
            try:
                name = metric.__name__
            except AttributeError:
                name = metric.func.__name__
                kws = metric.keywords
                for k in kws:
                    name += f"_{k}_{kws[k]}"
            log[name] = metric(tp, fp, tn, fn)
        self.log_dict(log)

    def test_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> Dict[str, torch.Tensor]:
        return self.validation_step(batch, batch_nb)

# Cell
class RNNAggDataModule(MILDataModule):
    def __init__(
            self,
            datafolder: Union[str, Path],
            data_csv: Union[str, Path],
            coord_csv: Union[str, Path],
            classes: Sequence[str],
            patches_per_slide=10,
            **kwargs
        ):
        super().__init__(datafolder, data_csv, coord_csv, classes, **kwargs)
        self.patches_per_slide = patches_per_slide


    def setup(self, stage: Optional[str] = None):
        self.data = (
            RNNSlideDataset.from_folder(
                self.datafolder,
                self.label_func,
                self.coord_csv,
                classes=self.classes,
                extensions=self.extensions,
                include=self.classes,
                train_percent=self.train_percent,
                size=self.size,
                level=self.level,
                patches_per_slide=self.patches_per_slide
            )
            .split_by_csv(self.data_csv)
            .to_tensor(tfms=self.tfms, tfm_y=False)
        )
        weights = np.float32(
            (self.data.train.labels == self.classes[0]).sum()
            / (self.data.train.labels == self.classes[1]).sum()
        )
        min_class = 1
        if weights < 1:
            weights = 1 / weights
            min_class = 0
        self.min_class = min_class
        self.weights = weights

# Cell
class RNNAggregator(ClassifModel):
    def __init__(self, rnn_hidden_dims: int = 128, **kwargs):
        super().__init__(**kwargs)
        self.freeze()
        nf = get_num_features(self.base_model)
        self.fc1 = nn.Linear(nf, rnn_hidden_dims)
        self.fc2 = nn.Linear(rnn_hidden_dims, rnn_hidden_dims)
        self.fc3 = nn.Linear(rnn_hidden_dims, self.hparams.n_classes)
        self.act = nn.ReLU()
        self.save_hyperparameters()

    def forward(self, x, state):
        x = _open_functions[self.hparams.open_mode](x).detach()
        if hasattr(self, "norm"):
            x = self.norm(x)
        x = self.base_model(x)
        x = self.fc1(x)
        state = self.fc2(state)
        state = self.act(state + x)
        y = self.fc3(state)
        return y, state

    def on_train_epoch_start(self):
        self.base_model.eval()

    def training_step(
        self, batch: Tuple[List[torch.Tensor], torch.Tensor], batch_nb: int
    ):
        xs, y = batch
        state = torch.zeros(x.shape[0], self.hparams.rnn_hidden_dims)
        for x in xs:
            y_hat, state = self(x, state)
        loss = self.loss(y_hat, y)
        lr = self.sched.optimizer.param_groups[-1]["lr"]
        log = {"train_loss": loss.detach(), "learning_rate": lr}
        self.log_dict(log, on_step=True, on_epoch=False)
        return loss

    def validation_step(
        self, batch: Tuple[List[torch.Tensor], torch.Tensor], batch_nb: int
    ) -> Dict[str, torch.Tensor]:
        # OPTIONAL
        xs, y = batch
        n = y.shape[0]
        state = torch.zeros(n, self.hparams.rnn_hidden_dims)
        for x in xs:
            y_hat, state = self(x, state)
        loss = self.loss(y_hat, y).detach()
        ret = {"loss": loss}
        y_hat = torch.softmax(y_hat, dim=1)
        y_hat = y_hat.argmax(dim=-1).view(n, -1)
        y = y.view(n, -1)
        for cl in self.hparams.classes:
            ret[f"t_{cl}"] = ((y_hat == cl) & (y == cl)).float().sum()
            ret[f"f_{cl}"] = ((y_hat == cl) & (y != cl)).float().sum()
        return ret

    def predict(self, xs: List[torch.Tensor]) -> torch.Tensor:
        state = torch.zeros(x.shape[0], self.hparams.rnn_hidden_dims)
        for x in xs:
            pred, state = super().predict(x, state)
        pred = torch.softmax(pred, dim=1)
        return pred

# Cell
class CoTeachingModel(BaseModule):
    """"""
    def __init__(
        self, n_classes: int = 2, classes: Optional[Sequence[str]] = None, **kwargs
    ):
        super().__init__(**kwargs)
        classes = ifnone(classes, list(range(n_classes)))
        n_classes = len(classes)  # if classes is specified it superseeds n_classes
        self.save_hyperparameters()
        hparams = self.hparams
        self.loss = _get_loss(
            hparams.loss, 1.0, "none", device=self.main_device, nc=n_classes
        )
        base_model1 = get_base_model(hparams.model, pretrained=not hparams.rand_weights)
        base_model2 = get_base_model(hparams.model, pretrained=not hparams.rand_weights)
        nf = get_num_features(base_model1)
        head1 = get_head(nf, n_classes, dropout=hparams.dropout)
        head2 = get_head(nf, n_classes, dropout=hparams.dropout)
        self.model1 = Classifier(base_model1, head1)
        self.model2 = Classifier(base_model2, head2)
        self.model2.apply(nn.init.kaiming_normal_)
        self.post_init()
        self._create_normalizer()

    def configure_optimizers(self) -> Union[Optimizer, Dict[str, Any]]:
        # REQUIRED
        hparams = self.hparams
        try:
            weight = hparams.weight if hparams.sample_mode == 0 else 1.0
        except AttributeError:
            weight = 1.0
        if not hasattr(self, "loss"):
            self.loss = _get_loss(
                hparams.loss, weight, hparams.reduction, device=self.main_device
            )
        self.lr = hparams.lr
        self.wd = hparams.wd
        self.opt1 = torch.optim.Adam(self.model1.parameters(), lr=self.lr)
        self.opt1 = torch.optim.Adam(self.model2.parameters(), lr=self.lr)
        n_train_dl = len(self.trainer.datamodule.train_dataloader())
        n_iter = int(hparams.epochs * n_train_dl)
        sched1 = _get_scheduler(self.opt1, hparams.sched, n_iter, self.lr)
        sched2 = _get_scheduler(self.opt2, hparams.sched, n_iter, self.lr)
        if sched1 is None:
            return self.opt1, self.opt2
        else:
            self.sched1 = sched1["scheduler"]
            self.sched2 = sched2["scheduler"]
            return [self.opt1, self.opt2], [self.sched1, self.sched2]

    def on_train_epoch_start(self):
        epoch = self.trainer.current_epoch
        epoch_max = self.trainer.max_epoch + 1
        eps = self.hparams.forget_rate
        n = self.hparams.forget_steps
        self.remember_rate = 1 - eps * min(1 + (epoch - n) / (epoch_max - n), epoch / n)

    def get_losses(self, batch: Tuple[torch.Tensor, torch.Tensor]):
        x, y = batch
        num_remember = int(self.remember_rate * len(y))
        y1 = self(x, model_idx=1)
        y2 = self(x, model_idx=2)
        loss1 = self.loss(y1, y).detach()
        loss2 = self.loss(y2, y).detach()

        if self.hparams.disagree_only:
            pred1 = torch.softmax(y1, dim=1).argmax(dim=1).detach()
            pred2 = torch.softmax(y1, dim=1).argmax(dim=1).detach()
            disagree_idxs = (pred1 != pred2).cpu().data
            idx1_sorted = np.lexsort((loss1.cpu().data, ~disagree_idxs))
            idx2_sorted = np.lexsort((loss2.cpu().data, ~disagree_idxs))
        else:
            idx1_sorted = torch.argsort(loss1)
            idx2_sorted = torch.argsort(loss2)

        y1 = y1[idx2_sorted[:num_remember]]
        y2 = y2[idx1_sorted[:num_remember]]
        loss1 = self.loss(y1, y[idx2_sorted[:num_remember]]).mean()
        loss2 = self.loss(y2, y[idx2_sorted[:num_remember]]).mean()
        return loss1, loss2, y1.detach(), y2.detach()

    def training_step(
        self,
        batch: Tuple[torch.Tensor, torch.Tensor],
        batch_nb: int,
        optimizer_idx: int,
    ) -> torch.Tensor:
        # REQUIRED
        loss1, loss2, _, _ = self.get_losses(batch)
        opt1, opt2 = self.optimizers()
        self.manual_backward(loss1, opt1)
        self.manual_backward(loss2, opt2)
        self.manual_optimizer_step(opt1)
        self.manuam_optimizer_step(opt2)
        lr = self.sched.optimizer.param_groups[-1]["lr"]
        log = {
            "train_loss1": loss1.detach(),
            "train_loss2": loss2.detach(),
            "learning_rate": lr,
        }
        self.log_dict(log, on_step=True, on_epoch=False)

    def validation_step(
        self, batch: Tuple[torch.Tensor, torch.Tensor], batch_nb: int
    ) -> Dict[str, torch.Tensor]:
        # OPTIONAL
        loss1, loss2, y1, y2 = self.get_losses(batch)
        ret = {"loss1": loss1, "loss2": loss2}
        _, y = batch
        n = y.shape[0]
        y = y.view(n, -1)
        y1 = torch.softmax(y1, dim=1)
        y1 = y1.argmax(dim=-1).view(n, -1)
        y2 = torch.softmax(y2, dim=1)
        y2 = y2.argmax(dim=-1).view(n, -1)
        for cl in self.hparams.classes:
            for k, y_hat in zip((1, 2), (y1, y2)):
                ret[f"t_{cl}_{k}"] = ((y_hat == cl) & (y == cl)).float().sum()
                ret[f"f_{cl}_{k}"] = ((y_hat == cl) & (y != cl)).float().sum()
        return ret

    def validation_epoch_end(self, outputs: List[Dict[str, torch.Tensor]]):
        # OPTIONAL
        log = {}
        for n in (1, 2):
            t_keys = [f"t_{cl}_{n}" for cl in self.hparams.classes]
            f_keys = [f"f_{cl}_{n}" for cl in self.hparams.classes]
            t = _get_keys_in_list_and_apply(outputs, *t_keys, apply_func=sum)
            f = _get_keys_in_list_and_apply(outputs, *f_keys, apply_func=sum)
            t = torch.stack(t)
            f = torch.stack(f)
            for metric in self.metrics:
                try:
                    name = metric.__name__
                except AttributeError:
                    name = metric.func.__name__
                    kws = metric.keywords
                    for k in kws:
                        name += f"_{k}_{kws[k]}"
                for k, cl in enumerate(self.hparams.classes):
                    c_name = name + f"_{cl}_{n}"
                    log[c_name] = metric(
                        t[k],
                        f[k],
                        t[:k].sum() + t[k + 1 :].sum(),
                        f[:k].sum() + f[k + 1 :].sum(),
                    )
                log[f"val_loss{n}"] = torch.mean(
                    torch.stack([output[f"loss{n}"] for output in outputs])
                )
        self.log_dict(log)

    def forward(self, x: torch.Tensor, model_idx=1) -> torch.Tensor:
        x = _open_functions[self.hparams.open_mode](x).detach()
        if hasattr(self, "norm"):
            x = self.norm(x)
        x = getattr(self, f"model{model_idx}")(x)
        return x

    def predict(self, x: torch.Tensor) -> torch.Tensor:
        pred = super().predict(x)
        pred = torch.softmax(pred, dim=1)
        return pred

    def freeze_base(self):
        """
        Freeze the base model.
        """
        for m in self.leaf_modules:
            if "base_model" in m.name and not isinstance(m, nn.BatchNorm2d):
                for param in m.parameters():
                    param.requires_grad = False

    def fit(self, dm: pl.LightningDataModule, **kwargs):
        super().fit(dm, automatic_optimization=False, **kwargs)